version: '3.8'

services:
    python-dev-container:
        build:
            context: .
            dockerfile: ./Dockerfile
            env_file: 
              ./.env
            args: 
              - USERNAME=${USERNAME}
              - VARIANT=${VARIANT}
        volumes:
            - .:/app
            - ..:/workspace:cached
            #Maybe none of this but a shared temp folder or something? 
        environment:
            - USERNAME=user-name-goes-here
        # Overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"